services:
  offensive-security:
    image: agnusdei1207/offensive-security:latest
    container_name: offensive-security
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_MODULE
    network_mode: host
    volumes:
      - offensive-vol:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
    command: sleep infinity

volumes:
  offensive-vol:
    name: offensive-vol
