services:
  offensive-security:
    image: agnusdei1207/offensive-security:latest
    container_name: offensive-security
    platform: linux/amd64
    cap_add:
      - NET_ADMIN
    volumes:
      - offensive-vol:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "6666:6666"
    command: sleep infinity

volumes:
  offensive-vol:
    name: offensive-vol
